name: CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, ci]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    - name: Install dependencies
      run: flutter pub get

    - name: Build apk
      run: flutter build apk
      
  linter:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Check for formatting issues
      run: flutter format --set-exit-if-changed .
    
    - name: Statically analyze code
      run: flutter analyze .
        
  tests:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run widget tests
      run: flutter test  
      
        path: build/app/outputs/apk/release/app-release.apk
