name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/UNIZAR-30226-2021-07/app/projects/1'
