name: release

on:
  release:
    types: [created]
    
jobs:
  release:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    # Setup Java environment in order to build the Android app.
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get

    # Build apk.
    - run: flutter build apk

    - name: Upload release apk
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: build/app/outputs/apk/release/app-release.apk
        asset_name: gatovid.apk
        # https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
        asset_content_type: application/vnd.android.package-archive
